spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_comm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lilong
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181


  # ===================================================================
  # 分布式文件系统FDFS配置
  # ===================================================================
fdfs:
  so-timeout: 15001
  connect-timeout: 15001
  thumb-image:             #缩略图生成参数,一般头像使用,根据需求配置
    width: 100
    height: 100
  tracker-list[0]: 47.96.141.103:22122

